Add graphviz as a required feature for examples/simple.rs
`cargo test` fails because examples.simple.rs fails to build
with the error:

error[E0432]: unresolved import `iptrie::graphviz`
 --> examples/simple.rs:2:13
  |
2 | use iptrie::graphviz::DotWriter;
  |             ^^^^^^^^ could not find `graphviz` in `iptrie`
  |

This commit adds graphviz as a required feature for
examples/simple.rs so it compiles and `cargo test` succeeds.